#!/bin/bash -e

# The create-metadata-file.sh script is used for resources that are parsed using the datasource file parser library
# before being converted to RDF. For files that are downloaded and directly imported into KaBOB, e.g. the Reactome
# BioPax formatted file, an accompanying RDF file containing metadata statements is generated by this script.
#
# FILENAME must be an absolute path
# DOWNLOAD_URL is optional

FILENAME=$1
RECORDSET_PREFIX=$2
DOWNLOAD_URL="${3:-n/a}"

METADATA_FILENAME="${FILENAME}.ready.nt"
FILE_SIZE=$(stat -c%s "${FILENAME}")
DATE=$(echo $(date +%F))
a=$(stat -c %y "${FILENAME}")
LAST_MOD_DATE=$(date --date="${a}" +%F)

UUID=$(cat /proc/sys/kernel/random/uuid)
RECORDSET_ID=$(echo "${RECORDSET_PREFIX}_$(date +%Y%m%d)")

echo "<http://ccp.ucdenver.edu/obo/ext/DS_${RECORDSET_ID}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ccp.ucdenver.edu/obo/ext/IAO_EXT_0000012> ." > "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/DS_${RECORDSET_ID}> <http://purl.org/dc/terms/date>\"${DATE}T00:00:00.000Z\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/DS_${RECORDSET_ID}> <http://purl.org/dc/elements/1.1/source> <http://ccp.ucdenver.edu/obo/ext/S_${UUID}> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/S_${UUID}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/IAO_0000310> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/S_${UUID}> <http://ccp.ucdenver.edu/obo/ext/DC_EXT_0000000>\"${DATE}T00:00:00.000Z\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/S_${UUID}> <http://ccp.ucdenver.edu/obo/ext/DC_EXT_0000001>\"${LAST_MOD_DATE}T00:00:00.000Z\"^^<http://www.w3.org/2001/XMLSchema#dateTime> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/S_${UUID}> <http://ccp.ucdenver.edu/obo/ext/DC_EXT_0000002>\"${FILE_SIZE}\"^^<http://www.w3.org/2001/XMLSchema#integer> ." >> "${METADATA_FILENAME}"
echo "<http://ccp.ucdenver.edu/obo/ext/S_${UUID}> <http://purl.org/dc/elements/1.1/source> <${DOWNLOAD_URL}> ." >> "${METADATA_FILENAME}"